#!/bin/bash

MMARVEL_BASE_PATH="/media/wlodder/T9/Datasets/Experiments/XAI/Military_Marvel"
MMARVEL_DATA_PATH=$MMARVEL_BASE_PATH/data
TRAIN_MMARVEL_PATH=$MMARVEL_BASE_PATH/train/data
TEST_MMARVEL_PATH=$MMARVEL_BASE_PATH/test/data
PUSH_MMARVEL_PATH=$TRAIN_MMARVEL_PATH
